const codingConcepts = [
  {
    id: "html-p",
    topic: "HTML",
    type: "cloze",
    prompt: "<p> creates a _____ on the page.",
    answer: "paragraph",
    explanation: "The <p> element is used for a paragraph of text.",
  },
  {
    id: "html-h1",
    topic: "HTML",
    type: "cloze",
    prompt: "<h1> creates the _____ heading on a page.",
    answer: "main or highest-level",
    explanation: "A page normally uses one <h1> for its primary heading.",
  },
  {
    id: "html-h2",
    topic: "HTML",
    type: "cloze",
    prompt: "<h2> creates a _____-level heading.",
    answer: "second",
    explanation: "<h2> headings organize sections beneath the main <h1>.",
  },
  {
    id: "html-button",
    topic: "HTML",
    type: "cloze",
    prompt: "<button> creates an _____ control the user can press.",
    answer: "interactive",
    explanation: "JavaScript can listen for a button click and respond to it.",
  },
  {
    id: "html-input",
    topic: "HTML",
    type: "multiple-choice",
    prompt: "What does an <input> element give the user?",
    options: ["A place to enter information", "A page heading", "Outside spacing"],
    answer: "A place to enter information",
    explanation: "Inputs collect information such as a song title or artist name.",
  },
  {
    id: "html-div",
    topic: "HTML",
    type: "cloze",
    prompt: "A <div> is a general-purpose _____ for grouping content.",
    answer: "container",
    explanation: "A <div> groups elements so they can be organized or styled together.",
  },
  {
    id: "html-ul-li",
    topic: "HTML",
    type: "multiple-choice",
    prompt: "Which statement correctly compares <ul> and <li>?",
    options: [
      "<ul> contains the list; <li> is one list item",
      "<li> contains the list; <ul> is one list item",
      "They both create buttons",
    ],
    answer: "<ul> contains the list; <li> is one list item",
    explanation: "The unordered list is the container, and each list item goes inside it.",
  },
  {
    id: "html-id",
    topic: "HTML + JavaScript",
    type: "cloze",
    prompt: "An HTML id is like a unique name tag or _____ pin for an element.",
    answer: "location",
    explanation: "JavaScript can use the unique id to find one specific element.",
  },
  {
    id: "css-role",
    topic: "CSS",
    type: "cloze",
    prompt: "HTML controls structure; CSS controls _____.",
    answer: "appearance",
    explanation: "CSS handles color, spacing, typography, layout, and other visual styles.",
  },
  {
    id: "css-margin",
    topic: "CSS",
    type: "multiple-choice",
    prompt: "Where does margin add space?",
    options: ["Outside an element", "Inside an element", "Inside JavaScript"],
    answer: "Outside an element",
    explanation: "Margin separates an element from the things around it.",
  },
  {
    id: "css-padding",
    topic: "CSS",
    type: "multiple-choice",
    prompt: "Where does padding add space?",
    options: ["Inside an element", "Outside an element", "Between JavaScript files"],
    answer: "Inside an element",
    explanation: "Padding creates room between an element's content and its border.",
  },
  {
    id: "css-grid",
    topic: "CSS",
    type: "cloze",
    prompt: "CSS Grid helps arrange items into rows and _____.",
    answer: "columns",
    explanation: "You used Grid to place fields and panels into organized layouts.",
  },
  {
    id: "responsive-layout",
    topic: "CSS",
    type: "cloze",
    prompt: "A _____ layout rearranges itself to fit different screen sizes.",
    answer: "responsive",
    explanation: "Responsive layouts keep a page usable on phones, tablets, and desktops.",
  },
  {
    id: "hero-section",
    topic: "Design",
    type: "multiple-choice",
    prompt: "What is a hero section?",
    options: [
      "The prominent opening section of a page",
      "A hidden JavaScript variable",
      "The final item in a list",
    ],
    answer: "The prominent opening section of a page",
    explanation: "A hero introduces the page, sets its visual mood, and communicates its purpose.",
  },
  {
    id: "visual-hierarchy",
    topic: "Design",
    type: "cloze",
    prompt: "Visual hierarchy helps the most important information stand out _____.",
    answer: "first",
    explanation: "Size, placement, color, and spacing guide the order in which content is noticed.",
  },
  {
    id: "javascript-role",
    topic: "JavaScript",
    type: "cloze",
    prompt: "HTML is structure, CSS is appearance, and JavaScript adds _____.",
    answer: "behavior",
    explanation: "JavaScript makes the page respond to actions and change over time.",
  },
  {
    id: "document",
    topic: "JavaScript",
    type: "cloze",
    prompt: "In the Life360 analogy, document is the entire _____.",
    answer: "map",
    explanation: "In JavaScript, document represents the webpage that JavaScript can search and change.",
  },
  {
    id: "get-element-by-id",
    topic: "JavaScript",
    type: "cloze",
    prompt: "document.getElementById() finds one HTML element using its unique _____.",
    answer: "id",
    explanation: "It is like using Life360 to find one specific person or place by its unique label.",
  },
  {
    id: "const-reference",
    topic: "JavaScript",
    type: "cloze",
    prompt: "In const songTitleInput = document.getElementById(\"song-title\"), songTitleInput is JavaScript's _____ for the element.",
    answer: "nickname or named reference",
    explanation: "The name points to the element so the full search does not need to be repeated.",
  },
  {
    id: "const-meaning",
    topic: "JavaScript",
    type: "multiple-choice",
    prompt: "What does const mean in this code?",
    code: 'const songTitleInput = document.getElementById("song-title");',
    options: [
      "The named reference cannot be reassigned to something else",
      "The user cannot type in the input",
      "The HTML element can never change",
    ],
    answer: "The named reference cannot be reassigned to something else",
    explanation: "The input's value can change. const only prevents reassigning the variable itself.",
  },
  {
    id: "input-value",
    topic: "JavaScript",
    type: "cloze",
    prompt: "songTitleInput.value reads what the user _____ into the input.",
    answer: "typed",
    explanation: "The .value property contains the input's current value.",
  },
  {
    id: "text-content",
    topic: "JavaScript",
    type: "cloze",
    prompt: "The textContent property changes an element's visible _____.",
    answer: "text",
    explanation: "Assigning a new string to textContent updates what the user sees.",
  },
  {
    id: "event-listener",
    topic: "JavaScript",
    type: "cloze",
    prompt: "addEventListener() tells JavaScript to listen for an _____ such as a click or submit.",
    answer: "event",
    explanation: "When that event happens, JavaScript runs the callback function you provide.",
  },
  {
    id: "prevent-default",
    topic: "JavaScript",
    type: "predict",
    prompt: "What does event.preventDefault() stop a form from doing?",
    answer: "It stops the form's normal page reload or submission behavior.",
    explanation: "This lets JavaScript process the form while the user stays on the same page.",
  },
  {
    id: "local-storage",
    topic: "JavaScript",
    type: "cloze",
    prompt: "localStorage lets a browser keep data between page _____.",
    answer: "visits or sessions",
    explanation: "Your Music Mood App uses localStorage so saved songs remain after the page closes.",
  },
  {
    id: "find-id-case",
    topic: "Find the mistake",
    type: "find-mistake",
    prompt: "Find the mistake in this line:",
    code: 'document.getElementByID("song-title");',
    answer: "ID should be Id: document.getElementById(\"song-title\");",
    explanation: "JavaScript is case-sensitive, and the method name ends with ById.",
  },
  {
    id: "find-value",
    topic: "Find the mistake",
    type: "find-mistake",
    prompt: "This code is supposed to read the user's input. What is missing?",
    code: "const songTitle = songTitleInput;",
    answer: "Add .value: const songTitle = songTitleInput.value;",
    explanation: "songTitleInput is the element. .value reads the text currently inside it.",
  },
  {
    id: "find-selector-match",
    topic: "Find the mistake",
    type: "find-mistake",
    prompt: "Why will JavaScript not find this input?",
    code: 'HTML: id="song-title"\nJavaScript: document.getElementById("songTitle")',
    answer: "The IDs do not match. JavaScript must search for \"song-title\".",
    explanation: "The text passed to getElementById() must exactly match the HTML id.",
  },
  {
    id: "javascript-let",
    topic: "JavaScript",
    type: "cloze",
    prompt: "let creates a variable whose value can be _____ later.",
    answer: "changed or reassigned",
    explanation: "Use let when the variable needs to hold a different value later, such as activeFilter.",
  },
  {
    id: "html-button-element",
    topic: "HTML",
    type: "cloze",
    prompt: "The <button> element creates a _____ control.",
    answer: "clickable",
    explanation: "A button gives the user something they can press to trigger an action.",
  },
  {
    id: "html-class-attribute",
    topic: "HTML",
    type: "cloze",
    prompt: "The class attribute connects an element to shared _____ rules.",
    answer: "CSS styling",
    explanation: "Several elements can share the same class and receive the same styles.",
  },
  {
    id: "html-equals-attribute",
    topic: "HTML",
    type: "cloze",
    prompt: "In class=\"mood-chip\", the equals sign connects the attribute name to its _____.",
    answer: "value",
    explanation: "Think of = as a label maker saying \"is\": class is mood-chip.",
  },
  {
    id: "html-button-type",
    topic: "HTML",
    type: "multiple-choice",
    prompt: "Why use type=\"button\" on a button that should not submit a form?",
    options: [
      "It prevents an accidental form submission",
      "It changes the button into an input",
      "It stores the selected mood",
    ],
    answer: "It prevents an accidental form submission",
    explanation: "A plain button inside or near a form should use type=\"button\" when its job is not submission.",
  },
  {
    id: "html-data-attribute",
    topic: "HTML + JavaScript",
    type: "cloze",
    prompt: "A data-* attribute stores custom information that _____ can read.",
    answer: "JavaScript",
    explanation: "For example, data-mood=\"Soft\" can be read with element.dataset.mood.",
  },
  {
    id: "data-mood-filter",
    topic: "HTML + JavaScript",
    type: "multiple-choice",
    prompt: "What is the difference between data-mood and data-filter in Music Mood App?",
    options: [
      "data-mood labels a song being saved; data-filter controls which songs are shown",
      "They always mean exactly the same thing",
      "data-filter styles the page; data-mood deletes songs",
    ],
    answer: "data-mood labels a song being saved; data-filter controls which songs are shown",
    explanation: "Their names describe two different jobs: storing a song's category and choosing the visible category.",
  },
  {
    id: "html-opening-closing-tags",
    topic: "HTML",
    type: "cloze",
    prompt: "Most HTML elements have an opening tag, content, and a _____ tag.",
    answer: "closing",
    explanation: "For example: <button>All</button>. The text between the tags is visible to the user.",
  },
  {
    id: "find-css-semicolon",
    topic: "Find the mistake",
    type: "find-mistake",
    prompt: "What is missing from this CSS variable declaration?",
    code: "--sage: #7c8f7a",
    answer: "A semicolon is missing: --sage: #7c8f7a;",
    explanation: "A semicolon marks the end of a CSS declaration so the next declaration can begin clearly.",
  },
  {
    id: "python-indent",
    topic: "Python",
    type: "cloze",
    prompt: "Python uses _____ to define blocks of code.",
    answer: "indentation",
    explanation: "Indentation matters in Python because it shows which statements belong together.",
  },
  {
    id: "python-lists",
    topic: "Python",
    type: "multiple-choice",
    prompt: "Which Python data type is a mutable ordered collection?",
    options: ["List", "Tuple", "String"],
    answer: "List",
    explanation: "Lists can be changed after they are created, which makes them flexible for app work.",
  },
  {
    id: "sql-select",
    topic: "SQL",
    type: "cloze",
    prompt: "SQL uses the SELECT statement to _____ data from a table.",
    answer: "retrieve",
    explanation: "SELECT is the basic query for asking a database for information.",
  },
  {
    id: "sql-where",
    topic: "SQL",
    type: "multiple-choice",
    prompt: "What does a WHERE clause do in SQL?",
    options: [
      "Filters rows to match a condition",
      "Creates a new website page",
      "Styles a table row",
    ],
    answer: "Filters rows to match a condition",
    explanation: "WHERE narrows the result set so you only get the rows you want.",
  },
  {
    id: "sql-join-career",
    topic: "SQL",
    type: "cloze",
    prompt: "A SQL JOIN helps combine related _____ for analysis.",
    answer: "tables",
    explanation: "JOINs are useful when useful information is spread across more than one table.",
  },
  {
    id: "sql-business-question",
    topic: "SQL",
    type: "predict",
    prompt: "A product team asks: 'Which onboarding step causes the biggest drop-off?' What should SQL help answer first?",
    answer: "Which step has the largest drop in users from one step to the next.",
    explanation: "The first goal is to find the step where the biggest decrease happens so the team knows where the workflow breaks.",
  },
  {
    id: "python-csv",
    topic: "Python",
    type: "multiple-choice",
    prompt: "Why is Python useful when working with CSV files?",
    options: [
      "It can read, clean, and analyze tabular data",
      "It only draws pictures",
      "It replaces the database",
    ],
    answer: "It can read, clean, and analyze tabular data",
    explanation: "Python is a practical tool for opening files, cleaning data, and automating repeated work.",
  },
  {
    id: "python-pandas",
    topic: "Python",
    type: "cloze",
    prompt: "pandas is a Python library often used for data _____.",
    answer: "analysis",
    explanation: "pandas helps you inspect, clean, and analyze structured data.",
  },
  {
    id: "product-user",
    topic: "Product Thinking",
    type: "cloze",
    prompt: "Product thinking starts by identifying the _____.",
    answer: "user",
    explanation: "You need to know who is affected before deciding what to change.",
  },
  {
    id: "product-metric",
    topic: "Product Thinking",
    type: "multiple-choice",
    prompt: "Why does a product team pick a success metric?",
    options: [
      "To know whether the change actually helped",
      "To make the screen look fancy",
      "To avoid doing any testing",
    ],
    answer: "To know whether the change actually helped",
    explanation: "Metrics turn a vague idea of improvement into something you can measure.",
  },
  {
    id: "systems-root-cause",
    topic: "Systems Thinking",
    type: "cloze",
    prompt: "Systems thinking looks for the _____ cause, not just the symptom.",
    answer: "root",
    explanation: "You want to understand why the workflow is failing, not only where it shows up.",
  },
  {
    id: "workflow-breaks",
    topic: "Workflow Thinking",
    type: "multiple-choice",
    prompt: "What is the best first question when a workflow seems broken?",
    options: [
      "Where does the process stop or slow down?",
      "What font should the page use?",
      "How many buttons can fit on the screen?",
    ],
    answer: "Where does the process stop or slow down?",
    explanation: "Workflow analysis starts by locating the point of friction or failure.",
  },
  {
    id: "communication-summary",
    topic: "Technical Communication",
    type: "predict",
    prompt: "What is the main goal of a concise technical summary?",
    answer: "To explain the problem, the finding, and the next action clearly.",
    explanation: "Short summaries help other people understand the result without reading every detail.",
  },
  {
    id: "typescript-types",
    topic: "TypeScript",
    type: "cloze",
    prompt: "TypeScript adds _____ to JavaScript.",
    answer: "types",
    explanation: "Types help catch mistakes earlier and make larger codebases easier to maintain.",
  },
  {
    id: "typescript-interface",
    topic: "TypeScript",
    type: "multiple-choice",
    prompt: "What is an interface in TypeScript used for?",
    options: [
      "Describing the shape of an object",
      "Running SQL queries",
      "Replacing CSS variables",
    ],
    answer: "Describing the shape of an object",
    explanation: "Interfaces define the properties an object should have.",
  },
  {
    id: "java-class",
    topic: "Java",
    type: "cloze",
    prompt: "In Java, a _____ is a blueprint for creating objects.",
    answer: "class",
    explanation: "Classes define fields and methods for objects created from them.",
  },
  {
    id: "java-compile",
    topic: "Java",
    type: "multiple-choice",
    prompt: "What does Java compile to before running?",
    options: ["Bytecode", "HTML", "CSS"],
    answer: "Bytecode",
    explanation: "Java code is compiled and then run on the Java Virtual Machine.",
  },
  {
    id: "csharp-properties",
    topic: "C#",
    type: "cloze",
    prompt: "C# properties are a common way to control access to an object's _____.",
    answer: "data",
    explanation: "Properties let you manage how values are read or changed.",
  },
  {
    id: "csharp-namespace",
    topic: "C#",
    type: "multiple-choice",
    prompt: "What is a namespace in C# used for?",
    options: [
      "Grouping related code and avoiding name conflicts",
      "Editing browser colors",
      "Replacing HTML tags",
    ],
    answer: "Grouping related code and avoiding name conflicts",
    explanation: "Namespaces organize code so symbols from different libraries do not clash.",
  },
  {
    id: "go-goroutine",
    topic: "Go",
    type: "cloze",
    prompt: "A Go _____ is a lightweight unit of concurrent work.",
    answer: "goroutine",
    explanation: "Goroutines help Go programs do many things at once efficiently.",
  },
  {
    id: "go-slices",
    topic: "Go",
    type: "multiple-choice",
    prompt: "What is a slice in Go?",
    options: [
      "A flexible view into an array",
      "A type of HTML tag",
      "A CSS layout mode",
    ],
    answer: "A flexible view into an array",
    explanation: "Slices are a common way to work with sequences of data in Go.",
  },
  {
    id: "swift-struct",
    topic: "Swift",
    type: "cloze",
    prompt: "Swift often uses _____ to model lightweight data types.",
    answer: "structs",
    explanation: "Structs are a core Swift type for organizing values and behavior.",
  },
  {
    id: "swift-optionals",
    topic: "Swift",
    type: "multiple-choice",
    prompt: "What does an optional mean in Swift?",
    options: [
      "A value may be present or absent",
      "A CSS rule that can be skipped",
      "A button that never works",
    ],
    answer: "A value may be present or absent",
    explanation: "Optionals help Swift represent values that might be nil.",
  },
];
